# pnpm-workspace.yaml
packages:
  # executable/launchable applications
  # - 'apps/*'
  # all config packages
  - 'config/*'
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  