name: Cache Modules
description: Cache modules
author: Primo

runs:
  using: composite
  steps:
    - name: 📁 Cache modules (pnpm)
      id: modules-cache
      uses: actions/cache@v3
      with:
        node-version-file: .nvmrc
        cache: pnpm
        key: cache-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}