name: 📦️ Install
description: Install packages
author: Primo

runs:
  using: composite
  steps:
    - name: 📦️ Dependencies
      id: dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile