name: 📦️ Install
description: Install packages
author: Primo

runs:
  using: composite
  steps:    
    - name: 📁 Cache (modules)
      uses: ./.github/actions/cache-modules

    - name: 🔺️ Cache (turbo)
      id: cache-turbo
      uses: ./.github/actions/cache-turbo
    
    - name: 📦️ Dependencies
      id: dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile