# .github/actions/lint/action.yml
name: Lint
description: Lint all files and packages
author: Primo

runs:
  using: composite
  steps:
    - name: 🚨️ Lint
      id: lint
      shell: bash
      run: |
        pnpm run lint