name: 🔺️ Cache (turbo)
description: Cache (turbo)
author: Primo

inputs:
  TOKEN:
    description: GitHub Token for Turbo
    required: true

runs:
  using: composite
  steps:
    - name: 🔺️ Cache (turbo)
      id: cache-turbo
      uses: actions/cache@v3
    
    - name: Turborepo local server
      # pinned the exact version with a commit hash to make sure that our GH token isn't used inappropriately by this third-party GH action
      uses: felixmosh/turborepo-gh-artifacts@90863ce9f52eb50906a199bfc79aa48ba1b4cf1c
      with:
        repo-token: ${{ inputs.TOKEN }}