name: 🔺️ Cache (turbo)
description: Cache (turbo)
author: Primo

runs:
  using: composite
  steps:
    - name: 🔺️ Cache (turbo)
      id: cache-turbo
      uses: actions/cache@v3
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-