---
name: Commit

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn setup
      - run: yarn build
    
    timeout-minutes: 5
