---
name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged

    steps:
      - name: Checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v2.0.0
        with:
          ref: master

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Build
        run: yarn && yarn build
      
      - name: Publish
        run: yarn multi-semantic-release --execasync
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    timeout-minutes: 5